/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import academico.Aluno;
import academico.Curso;
import academico.Matricula;
import javax.swing.JOptionPane;

/**
 *
 * @author Junim Roberti
 */
public class CadastrarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarMatricula
     */
    private Matricula matricula1;
    private Curso curso1;
    private Aluno aluno1;
    public CadastrarMatricula() {
        initComponents();
    }
    public CadastrarMatricula(Matricula matricula, Aluno aluno, Curso curso){
          this.matricula1 = matricula;
            this.matricula1 = matricula;
            this.aluno1 = aluno;
            this.curso1 = curso;
          initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sair = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        Enviar = new javax.swing.JButton();
        CadastrarMatricula = new javax.swing.JPanel();
        NumeroMatrículaLab = new javax.swing.JLabel();
        DataMatriculaLab = new javax.swing.JLabel();
        NumeroMatriculaText = new javax.swing.JTextField();
        DataMatriculaText = new javax.swing.JTextField();
        CodigoMatriculaCurText = new javax.swing.JTextField();
        CodigoMatriculaCurLab = new javax.swing.JLabel();
        CodigoMatriculaAluText = new javax.swing.JTextField();
        CodigoMatriculaAluLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        Enviar.setText("Enviar");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        CadastrarMatricula.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastrar Matricula"));

        NumeroMatrículaLab.setText("Numero de Matrícula:");

        DataMatriculaLab.setText("Data da Matrícula:");

        DataMatriculaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataMatriculaTextActionPerformed(evt);
            }
        });

        CodigoMatriculaCurLab.setText("Codigo do Curso:");

        CodigoMatriculaAluLab.setText("Codigo do Aluno:");

        javax.swing.GroupLayout CadastrarMatriculaLayout = new javax.swing.GroupLayout(CadastrarMatricula);
        CadastrarMatricula.setLayout(CadastrarMatriculaLayout);
        CadastrarMatriculaLayout.setHorizontalGroup(
            CadastrarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarMatriculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastrarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DataMatriculaLab)
                    .addComponent(NumeroMatrículaLab)
                    .addComponent(CodigoMatriculaCurLab)
                    .addComponent(CodigoMatriculaAluLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastrarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumeroMatriculaText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataMatriculaText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoMatriculaCurText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoMatriculaAluText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        CadastrarMatriculaLayout.setVerticalGroup(
            CadastrarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarMatriculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastrarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumeroMatrículaLab)
                    .addComponent(NumeroMatriculaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataMatriculaLab)
                    .addComponent(DataMatriculaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoMatriculaCurText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoMatriculaCurLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarMatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodigoMatriculaAluText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodigoMatriculaAluLab))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Enviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(Sair)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CadastrarMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CadastrarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Limpar)
                    .addComponent(Enviar)
                    .addComponent(Sair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        // TODO add your handling code here:
        NumeroMatriculaText.setText("");
        DataMatriculaText.setText("");
        CodigoMatriculaCurText.setText("");
        CodigoMatriculaAluText.setText("");
    }//GEN-LAST:event_LimparActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:
        if (NumeroMatriculaText.getText().isEmpty() || CodigoMatriculaAluText.getText().isEmpty() || CodigoMatriculaCurText.getText().isEmpty() || DataMatriculaText.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos!");
        }else{
        //int JP = 0;
        boolean aux = false;
        for(int i = 0;i<aluno1.getArrayAluno().size();i++){
            if(aluno1.getArrayAluno().get(i).getCodigo() == Integer.parseInt(CodigoMatriculaAluText.getText())){
                aux = true;
            }
        }
        for(int i = 0;i < curso1.getArrayCurso().size();i++){
            if(curso1.getArrayCurso().get(i).getCodigo() == Integer.parseInt(CodigoMatriculaCurText.getText())){
                aux = true;
            }
        }
        if(aux == false){
            JOptionPane.showMessageDialog(null, "Aluno ou Curso nao existente");
            CodigoMatriculaCurText.setText("");
            CodigoMatriculaAluText.setText("");
        }else{
            Matricula matricula2 = new Matricula();
            matricula2.lerDadosMatricula(matricula2, NumeroMatriculaText.getText(), CodigoMatriculaAluText.getText(), CodigoMatriculaCurText.getText(), DataMatriculaText.getText());
            matricula1.setArrayMatricula(matricula2);
            JOptionPane.showMessageDialog(null, "Matricula Cadastrada!!", "Sistema Academico", 1);
        //JP = JOptionPane.showConfirmDialog(null, "Você deseja fazer outra Matricula?", "Sistema Academico", 0, 3);
        //if(JP == 0){
            dispose();
        //    CadastrarAluno frame = new CadastrarAluno();
        //    frame.setLocationRelativeTo(null);
        //    frame.setDefaultCloseOperation(frame.DISPOSE_ON_CLOSE);
        //    frame.setVisible(true);
        //}else{
        //    dispose();
       // }
        }
        }
    }//GEN-LAST:event_EnviarActionPerformed

    private void DataMatriculaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataMatriculaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DataMatriculaTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarMatricula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastrarMatricula;
    private javax.swing.JLabel CodigoMatriculaAluLab;
    private javax.swing.JTextField CodigoMatriculaAluText;
    private javax.swing.JLabel CodigoMatriculaCurLab;
    private javax.swing.JTextField CodigoMatriculaCurText;
    private javax.swing.JLabel DataMatriculaLab;
    private javax.swing.JTextField DataMatriculaText;
    private javax.swing.JButton Enviar;
    private javax.swing.JButton Limpar;
    private javax.swing.JTextField NumeroMatriculaText;
    private javax.swing.JLabel NumeroMatrículaLab;
    private javax.swing.JButton Sair;
    // End of variables declaration//GEN-END:variables
}
